# flask-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app
  labels:
    app: flask
spec:
  type: ClusterIP # Exposes the service internally within the cluster
  ports:
  - port: 80 # The port the service will expose
    targetPort: 5000 # The port the Flask app listens on
    protocol: TCP
  selector:
    app: flask # Matches the app label in the Deployment
